apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ibrahim3321/final-project    
    targetRevision: main                                  
    path: k8s/monitoring                                   
    helm:
      valueFiles:
        - values-prometheus.yaml                          
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 3

