global:
  image:
    tag: v2.11.6   
controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

repoServer:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

applicationSet:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 256Mi

server:
  replicas: 1

  extraArgs:
    - --insecure

  service:
    type: LoadBalancer
    ports:
      http: 80
      https: 443
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "false"  

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi


notifications:
  enabled: false

dex:
  enabled: true

configs:
  params:
    server.insecure: true
    applicationsetcontroller.enable.progressive.syncs: true

  cm:
    timeout.reconciliation: 30s

  rbac:
    policy.default: role:readonly

