admin:
  existingSecret: grafana-admin-credentials
  userKey: admin-user
  passwordKey: admin-password

service:
  type: LoadBalancer
  port: 80

persistence:
  enabled: true
  size: 10Gi

deploymentStrategy:
  type: Recreate

ingress:
  enabled: false

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:80
        isDefault: true
        editable: false
        jsonData:
          timeInterval: 15s

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

