name: Build & Push Images
on:
  workflow_dispatch:

env:
  IMAGE_BACKEND: backend
  IMAGE_FRONTEND: frontend
  ACR_NAME: ${{ secrets.ACR_NAME }}

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Build & Push backend
        run: |
          ACR_LOGIN_SERVER=$ACR_NAME.azurecr.io
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_BACKEND:latest ./expensy_backend
          docker push $ACR_LOGIN_SERVER/$IMAGE_BACKEND:latest

      - name: Build & Push frontend
        run: |
          ACR_LOGIN_SERVER=$ACR_NAME.azurecr.io
          docker build -t $ACR_LOGIN_SERVER/$IMAGE_FRONTEND:latest ./expensy_frontend
          docker push $ACR_LOGIN_SERVER/$IMAGE_FRONTEND:latest

      - name: Trigger Deploy to AKS Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          repository: ${{ github.repository }}
          workflow: deploy_aks.yml
          ref: main
