name: Terraform + Build & Deploy (Full Stack)

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  IMAGE_BACKEND: backend
  IMAGE_FRONTEND: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Generate terraform.tfvars from secret
        working-directory: ./terraform
        run: |
          echo '${{ secrets.NAME_INFRA }}' > terraform.tfvars
          echo " Created terraform.tfvars:"
          cat terraform.tfvars

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Get Terraform Outputs
        id: tfoutput
        working-directory: ./terraform
        run: |
          ACR_NAME=$(terraform output -raw acr_name)
          AKS_NAME=$(terraform output -raw aks_name)
          RG_NAME=$(terraform output -raw resource_group_name)
          echo "acr_name=$ACR_NAME" >> $GITHUB_OUTPUT
          echo "aks_name=$AKS_NAME" >> $GITHUB_OUTPUT
          echo "rg_name=$RG_NAME" >> $GITHUB_OUTPUT

      - name: Login to ACR
        run: az acr login --name ${{ steps.tfoutput.outputs.acr_name }}

      - name: Build & Push backend
        run: |
          ACR_LOGIN_SERVER=${{ steps.tfoutput.outputs.acr_name }}.azurecr.io
          docker build -t $ACR_LOGIN_SERVER/${{ env.IMAGE_BACKEND }}:latest ./backend
          docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_BACKEND }}:latest

      - name: Build & Push frontend
        run: |
          ACR_LOGIN_SERVER=${{ steps.tfoutput.outputs.acr_name }}.azurecr.io
          docker build -t $ACR_LOGIN_SERVER/${{ env.IMAGE_FRONTEND }}:latest ./frontend
          docker push $ACR_LOGIN_SERVER/${{ env.IMAGE_FRONTEND }}:latest

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ steps.tfoutput.outputs.rg_name }} \
            --name ${{ steps.tfoutput.outputs.aks_name }} \
            --overwrite-existing

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f aks-yaml/

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/backend-deployment || true
          kubectl rollout status deployment/frontend-deployment || true

