name: Terraform Infrastructure
on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
      - run: echo '${{ secrets.NAME_INFRA }}' > ./terraform/terraform.tfvars
      - run: terraform -chdir=./terraform init
      - run: terraform -chdir=./terraform apply -auto-approve
